"use client";
import { useEffect, useState } from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";
import tel from "../utils/svg/Tel.svg";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    setTimeout(() => {
      setShowModal(true);
    }, 2500);
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {showModal && (
        <div
          className="h-screen w-full z-[99999]  fixed inset-0 flex justify-center items-center"
          style={{ backgroundColor: "rgba(0, 0, 0, 0.5)" }}
        >
          <div className="w-[370px]  bg-gray-200 border opacity-100 relative p-4 rounded-xl">
            <div
              className="absolute top-0 right-0 p-1 cursor-pointer"
              onClick={() => setShowModal(false)}
            >
              ✖
            </div>
            <p className="text-center text-2xl font-semibold">
              Join Our Telegram Group 
            </p>
            <p className="text-lg font-semibold mt-4">
              Join Our Telegram Group for:
            </p>
            <div className="flex justify-between items-end">
              <div className="space-y-2 text-sm text-gray-700 mt-2 font-semibold">
                <p>✅ 3-4 Daily Calls</p>
                <p>✅ Risk & Reward: 1:2/1:4 ++</p>
                <p>✅ Accuracy 90++</p>
                <p>✅ Expert Guidance</p>
                <p>✅ Min Capital: 15K</p>
              </div>
            </div>
            <button className="w-full bg-blue-200 p-2 text-xl font-semibold mt-5 rounded-lg">
              Join Now 👉{" "}
            </button>
          </div>
        </div>
      )}
    </html>
  );
}
